# Text vectorization techniques

In [20]:
import numpy as np
import pandas as pd
import sklearn

In [19]:
df = pd.DataFrame({'text': ['people watch campusx','campusx watch campusx','people write comment','campusx write comment'], 'output':[1,1,0,0]})

In [3]:
df

text  output
0   people watch campusx       1
1  campusx watch campusx       1
2   people write comment       0
3  campusx write comment       0

In [21]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer ()

In [8]:
bow = cv.fit_transform(df["text"])

In [10]:
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'campusx': 0, 'write': 4, 'comment': 1}


In [11]:
print(bow[0].toarray())
print(bow[1].toarray())

[[1 0 1 1 0]]
[[2 0 0 1 0]]


In [14]:
cv.transform(["people watch and write of comment "]).toarray()

array([[0, 1, 1, 1, 1]])

# Bigram

In [6]:
df = pd.DataFrame({'text': ['people watch campusx','campusx watch campusx','people write comment','campusx write comment'], 'output':[1,1,0,0]})

In [5]:
cv = CountVectorizer (ngram_range=(2,2))

In [7]:
bigram = cv.fit_transform(df["text"])

In [8]:
print(cv.vocabulary_)

{'people watch': 2, 'watch campusx': 4, 'campusx watch': 0, 'people write': 3, 'write comment': 5, 'campusx write': 1}


In [9]:
cv.transform(["people watch and write of comment "]).toarray()

array([[0, 0, 1, 0, 0, 0]])

# Trigram

In [10]:
cv = CountVectorizer (ngram_range=(3,3))

In [12]:
bow = cv.fit_transform(df["text"])

In [14]:
print(cv.vocabulary_)
print(len(cv.vocabulary_))

{'people watch campusx': 2, 'campusx watch campusx': 0, 'people write comment': 3, 'campusx write comment': 1}
4


# combination of unigram + bigram + trigram

In [16]:
cv = CountVectorizer (ngram_range=(1,3))

In [17]:
bow = cv.fit_transform(df["text"])

In [18]:
print(cv.vocabulary_)
print(len(cv.vocabulary_))

{'people': 6, 'watch': 11, 'campusx': 0, 'people watch': 7, 'watch campusx': 12, 'people watch campusx': 8, 'campusx watch': 1, 'campusx watch campusx': 2, 'write': 13, 'comment': 5, 'people write': 9, 'write comment': 14, 'people write comment': 10, 'campusx write': 3, 'campusx write comment': 4}
15


# TF- IDF

In [22]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
tfidf.fit_transform(df["text"]).toarray()

array([[0.49681612, 0.        , 0.61366674, 0.61366674, 0.        ],
       [0.8508161 , 0.        , 0.        , 0.52546357, 0.        ],
       [0.        , 0.57735027, 0.57735027, 0.        , 0.57735027],
       [0.49681612, 0.61366674, 0.        , 0.        , 0.61366674]])

In [ ]:
print(tfidf.)